name = "forgeowo"
author = "dealerke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d67c6b37faafa595fcc6c7fdba417d92f2727b1413e052f00b25bd87374dc41"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
